###
POST http://localhost:5250/api/create-role

### assign roles
POST http://localhost:5250/api/assign-role

### add claims
POST http://localhost:5250/api/add-claim
### 
POST http://localhost:5250/api/login

###
GET http://localhost:5250/

### 
GET http://localhost:5250/api/admin-only
Cookie: .AspNetCore.Identity.Application=CfDJ8GrIJqjZ88VNomlhtHHpSzNNkaChbyo8dpbV1RDPaNBmfVgdssxumSoYblZAQeqrx-3LTpUViGQH7mk4EX_XwTrfwGQC4SSI_84Dw8W6V8sLnAVwvmb_KPxSBMhgKTwSWnkw36ZDxbPGSfLTXEiCU6InsRuOl8uVfv3diMT4K5BdOabjUfZbmsqqeLUaFq3wCcmCh15ovRsV5N21w-J6pQgu1ZyDnxbdx7JZwZacKT2z-ufNpVhEI-LJTFFl_PQSb86dNSLIwdyZazRinyVCGc-siv0nOhkEFjknc_9xzHExMgGUMWH5tW8bhObQjjgnywwXJQWne_stP5dB0fP_h1Xa7eVZqC8R1Ad7_v4LqDNU-bXS8ipJipX8Gy3rrjzHYrGTGaMc0tM0Sga8ELhIrmRNCS2w26wv8NHbNvxo3MV6PSW5cGahPqXyekXiuCZs7oJYy_6rj5GK8QFnoqhmey2NjkiT1z2yjd0Onh1DU6pzVRU5qY_eXa0pY_3iRf2g2Z9FLZjbNT0IyWFujj5RvYBBScyqihGpK7tfFIx0jxUme8DJm1cus08w8IYkLnth9ZEVJV7JDz1KG-n_v_Xz1_4THg_mL7SAsV-VaGU1Gr8CBUZv1ofWb4lwxr0TBMOGU8dgMqVcb94hPIiuWSZMmcDLTHdUkJhqqorfqfUrTVcU_PQUqhFwetzYDLgHYDThZPRu4Ijh-sed2POodoAQwzcfY6DXY08B7QBiPLKlRNlr7O3zDy5CDysyCZm1YYgcKqbjAWwh4U7x9A7l64uZxgrs8kWkhv4LQirMzLdpjFxFoJ5zcPK6qzF21bBU2tcw6nGQf9tQlKlTN7W1OS0OOwQ; path=/; samesite=lax; httponly
### 
GET http://localhost:5250/api/user-claim-check
Cookie: .AspNetCore.Identity.Application=CfDJ8GrIJqjZ88VNomlhtHHpSzNNkaChbyo8dpbV1RDPaNBmfVgdssxumSoYblZAQeqrx-3LTpUViGQH7mk4EX_XwTrfwGQC4SSI_84Dw8W6V8sLnAVwvmb_KPxSBMhgKTwSWnkw36ZDxbPGSfLTXEiCU6InsRuOl8uVfv3diMT4K5BdOabjUfZbmsqqeLUaFq3wCcmCh15ovRsV5N21w-J6pQgu1ZyDnxbdx7JZwZacKT2z-ufNpVhEI-LJTFFl_PQSb86dNSLIwdyZazRinyVCGc-siv0nOhkEFjknc_9xzHExMgGUMWH5tW8bhObQjjgnywwXJQWne_stP5dB0fP_h1Xa7eVZqC8R1Ad7_v4LqDNU-bXS8ipJipX8Gy3rrjzHYrGTGaMc0tM0Sga8ELhIrmRNCS2w26wv8NHbNvxo3MV6PSW5cGahPqXyekXiuCZs7oJYy_6rj5GK8QFnoqhmey2NjkiT1z2yjd0Onh1DU6pzVRU5qY_eXa0pY_3iRf2g2Z9FLZjbNT0IyWFujj5RvYBBScyqihGpK7tfFIx0jxUme8DJm1cus08w8IYkLnth9ZEVJV7JDz1KG-n_v_Xz1_4THg_mL7SAsV-VaGU1Gr8CBUZv1ofWb4lwxr0TBMOGU8dgMqVcb94hPIiuWSZMmcDLTHdUkJhqqorfqfUrTVcU_PQUqhFwetzYDLgHYDThZPRu4Ijh-sed2POodoAQwzcfY6DXY08B7QBiPLKlRNlr7O3zDy5CDysyCZm1YYgcKqbjAWwh4U7x9A7l64uZxgrs8kWkhv4LQirMzLdpjFxFoJ5zcPK6qzF21bBU2tcw6nGQf9tQlKlTN7W1OS0OOwQ; path=/; samesite=lax; httponly